import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/common/(themes)/theme-provider";
import { AppContainer } from "@/components/app/(layouts)/app-container";
import Footer from "@/components/common/(footer)/footer";
import { ClerkProvider } from '@clerk/nextjs'
// import { Suspense } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      data-scroll-behavior="smooth"
    suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>

  <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <AppContainer>
              <div>
                <div className="hidden md:block">
              {/* <NotchNavbar/> */}


                </div>
                <div className="block md:hidden">

                  
                {/* <Navbar/> */}

                </div>

              </div>
            
               </AppContainer>
            {children}
             <AppContainer>
                <Footer/>
            
               </AppContainer>
          </ThemeProvider>      
                  </ClerkProvider>

          
          
            </body>
    </html>
  );
}
