import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/common/(themes)/theme-provider";
import { AppContainer } from "@/components/app/(layouts)/app-container";
import Footer from "@/components/common/(footer)/footer";
import { ClerkProvider } from '@clerk/nextjs'
import { Navbar } from "@/components/common/(navbar)/navbar";
import { NotchNavbar } from "@/components/ui/notch-navbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      data-scroll-behavior="smooth"
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* ClerkProvider reads the request's cookies server-side to
            determine signed-in/signed-out state. Under cacheComponents,
            that counts as an uncached dynamic read, so per Clerk's own
            Next.js 16 guidance it needs its own Suspense boundary — not
            just its children. */}
        <Suspense fallback={null}>
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <AppContainer>
                <div>
                  <div className="hidden md:block">
                    <Suspense fallback={null}>
                      <NotchNavbar />
                    </Suspense>
                  </div>
                  <div className="block md:hidden">
                    <Suspense fallback={null}>
                      <Navbar />
                    </Suspense>
                  </div>
                </div>
              </AppContainer>

              {/* Isolates whatever dynamic reads happen inside the actual
                  page (e.g. /blogs/[slug]) so the build can still
                  statically shell the surrounding layout chrome. */}
              <Suspense fallback={null}>{children}</Suspense>

              <AppContainer>
                <Footer />
              </AppContainer>
            </ThemeProvider>
          </ClerkProvider>
        </Suspense>
      </body>
    </html>
  );
}
